export default {
    GET_ALL_WORDS_SUCCEED :"GET_ALL_WORDS_SUCCEED",
    CHANGE_CURRENT_WORD_SUCCEED: "CHANGE_CURRENT_WORD_SUCCEED",
    UPDATE_WORD_SUCCEED: "UPDATE_WORD_SUCCEED",
    DELETE_WORD_SUCCEED: "DELETE_WORD_SUCCEED",
    ADD_WORD_SUCCEED: "ADD_WORD_SUCCEED"
}