export default {
    GET_ALL_WORDS_SUCCEED : 'GET_ALL_WORDS_SUCCEED',
    CHANGE_CURRENT_WORD_SUCCEED: 'CHANGE_CURRENT_WORD_SUCCEED',
    UPDATE_WORD_SUCCEED: 'UPDATE_WORD_SUCCEED',
    DELETE_WORD_SUCCEED: 'DELETE_WORD_SUCCEED',
    ADD_WORD_SUCCEED: 'ADD_WORD_SUCCEED',
    SEARCH_WORD_SUCCED: 'SEARCH_WORD_SUCCED',
    SORT_WORD_SUCCED: 'SORT_WORD_SUCCED',
    GET_WORD_BY_ID_SUCCEED: 'GET_WORD_BY_ID_SUCCEED',
}
